### PR TITLE
Stage 2 Backend

### PR DESCRIPTION
**Pull request by skovakina**
## Schemas and Models
- Implemented `User` (email, password, name) and `Article` (keyword, title, text, date, source, link, image, owner) schemas.

## Routes and Middleware
- **Articles**:
  - `GET /articles`: Retrieves all articles.
  - `POST /articles`: Adds an article
  - `DELETE /articles/:_id`: Deletes an article
- **Users**:
  - `GET /users/me`: Fetches current user info
  - `POST /signin`: User login
  - `POST /signup`: User registration
   
## Logging and Deployment
- Set up `request.log` and `error.log` for API requests and errors.
- Deployed API on a server, accessible via a domain name and HTTPS. `https://sko-news.mooo.com` `https://api.sko-news.mooo.com`

## Security and Validation
- Enforced password encryption and request data validation.
- Centralized error handling and managed HTTP status codes.
- Ensured user-specific article deletion.

### CODE REVIEW

**Comment by adzhenalieva** [comment]
# Summary:
## Backend

### Performance Criteria
- [x]  The repository contains all the necessary infrastructure files:
  - [x] `package.json`;
  - [x] `.editorconfig`;
  - [x] `.eslintrc` is required for extending the configuration of airbnb-base
		- [x] `package.json` contains the `devDependencies` needed for the linter to work correctly
		- [x] An exception for `_id` is added
		- [x] The following rules are forbidden: `eslint-disable`, `eslint-disable-line`, and `eslint-disable-next-line`
  - [x] `.gitignore` should contain at least the `node_modules` folder
- [x]  There are no lint errors. When running `npx eslint .` they should be absent.
- [x]  The scripts section of the package.json file contains the following:
  - [x] An `npm run start` command that starts the server on `localhost:3000`.
  - [x] An `npm run dev` command that starts the server on `localhost:3000` with hot reloading.
- [ ]  The following routes function as described:
  - [x] A request to `GET /users/me` returns information about the user (email and name).
  - [x] `POST /signup` creates a user with the data passed inside the request body.
  - [x] `POST /signin` returns a JWT when the correct email and password are passed in the request body.
  - [ ] `GET /articles` returns all articles saved by the user.
      _To get the data saved by the user you need to filter data by `owner` field, for example, https://snipboard.io/U6XVJs.jpg_
  - [x] `POST /articles` creates an article with the data passed inside the request body.
  - [x] `DELETE /articles/:articleId` deletes the saved article using `_id`.
- [x]  Users can't delete saved articles from other user profiles.
- [ ]  All routes are protected with authorization, except for `/signin` and `/signup`.
   _The 'getArticles' route also should be protected with the authorization_
- [x]  User routes and article routes are described in separate files.
- [x]  API errors are handled:
  - [x] Error status codes are used: 400, 401, 403, 404, 409, 500.
  - [x] If something is wrong with the request, the server returns a response with an error message and a corresponding status.
  - [x] The error message matches its type.
  - [x] Asynchronous handlers end with a `catch()` block.
  - [x] The API does not return standard database or Node.js errors.
- [x]  Safe password storage has been implemented:
  - [x] Passwords are stored in a hashed form.
  - [x] The API does not return a password hash to the client.
- [x]  Validation implemented correctly:
  - [x] Requests are validated before being passed to the controller. The body and (where applicable) headers and parameters are checked against the corresponding schemas. If a request doesn't match the schema, the processing is not passed to the controller and the client receives a validation error.
  - [x] Data is validated before being added to the database.
- [ ]  In production mode, the database address is taken from `process.env`.
    _The database address is hardcoded_
- [x]  The server can be accessed via HTTPS using the domain specified in README.md.
- [x]  Storing the secret key for creating a JWT is implemented correctly:
  - [x] In production (i.e., when deployed to the server), the secret key should be stored in a .env file, and this file should not be added to Git.
  - [x] In development (i.e., when run on localhost), the code should run and function correctly, even though there is no .env file present.

### Best Practices
- [ ]  All routes are connected to the `index.js` file, which is located in the `routes` folder, and `app.js` contains one main route handled by routes.
- [x]  Asynchronous operations are implemented using promises or async/await.
- [x]  Validation is described in a separate module.
- [x]  Logging is set up:
  - [x] All requests and responses are logged to the `request.log` file.
  - [x] All errors are logged to the `error.log` file.
  - [x] Log files aren't added to the git repository.
- [x]  Errors are handled by a centralized handler.
- [x]  Centralized error handling is described inside a separate module.
- [x]  The application API is located in an /api subdirectory or on an api. subdomain (not just name.zone)
  - [x] Correct:  domain-name.tk/api or api.domain-name.tk
  - [x] Incorrect: domain-name.tk


### Recommendations
- [x]  For API errors, classes have been created to extend the Error constructor.
- [x]  The Helmet module is used to set security-related headers.
- [ ]  Configuration and constants are stored in separate files:
  - [ ] The Mongo server address and the private key for the JWT in development mode are stored inside a separate configuration file.
  - [ ] Application constants (response and error messages) are stored inside a separate file with constants.
- [ ]  A rate limiter is set up: the number of requests from a single IP address is limited to a particular value in a given amount of time.
- [ ]  The rate limiter is configured in a separate file and imported into `app.js`.

## Number of points: 62

## Additional comments:
- Please, add the description of the project and its links to the README file
- When creating a new user the `email` and `_id` fields also should be returned in the response

**Comment by skovakina** [comment]
Hello! Thank you very much for your review!

**Comment by adzhenalieva** [comment]
# Summary:
## Backend

### Performance Criteria
- [x]  The repository contains all the necessary infrastructure files:
  - [x] `package.json`;
  - [x] `.editorconfig`;
  - [x] `.eslintrc` is required for extending the configuration of airbnb-base
		- [x] `package.json` contains the `devDependencies` needed for the linter to work correctly
		- [x] An exception for `_id` is added
		- [x] The following rules are forbidden: `eslint-disable`, `eslint-disable-line`, and `eslint-disable-next-line`
  - [x] `.gitignore` should contain at least the `node_modules` folder
- [x]  There are no lint errors. When running `npx eslint .` they should be absent.
- [x]  The scripts section of the package.json file contains the following:
  - [x] An `npm run start` command that starts the server on `localhost:3000`.
  - [x] An `npm run dev` command that starts the server on `localhost:3000` with hot reloading.
- [ ]  The following routes function as described:
  - [ ] A request to `GET /users/me` returns information about the user (email and name).
      _The route is missing 'users' in its path: https://snipboard.io/5McDqx.jpg_
  - [x] `POST /signup` creates a user with the data passed inside the request body.
  - [x] `POST /signin` returns a JWT when the correct email and password are passed in the request body.
  - [x] `GET /articles` returns all articles saved by the user.
  - [x] `POST /articles` creates an article with the data passed inside the request body.
  - [x] `DELETE /articles/:articleId` deletes the saved article using `_id`.
- [x]  Users can't delete saved articles from other user profiles.
- [x]  All routes are protected with authorization, except for `/signin` and `/signup`.
- [x]  User routes and article routes are described in separate files.
- [x]  API errors are handled:
  - [x] Error status codes are used: 400, 401, 403, 404, 409, 500.
  - [x] If something is wrong with the request, the server returns a response with an error message and a corresponding status.
  - [x] The error message matches its type.
  - [x] Asynchronous handlers end with a `catch()` block.
  - [x] The API does not return standard database or Node.js errors.
- [x]  Safe password storage has been implemented:
  - [x] Passwords are stored in a hashed form.
  - [x] The API does not return a password hash to the client.
- [x]  Validation implemented correctly:
  - [x] Requests are validated before being passed to the controller. The body and (where applicable) headers and parameters are checked against the corresponding schemas. If a request doesn't match the schema, the processing is not passed to the controller and the client receives a validation error.
  - [x] Data is validated before being added to the database.
- [x]  In production mode, the database address is taken from `process.env`.
- [x]  The server can be accessed via HTTPS using the domain specified in README.md.
- [x]  Storing the secret key for creating a JWT is implemented correctly:
  - [x] In production (i.e., when deployed to the server), the secret key should be stored in a .env file, and this file should not be added to Git.
  - [x] In development (i.e., when run on localhost), the code should run and function correctly, even though there is no .env file present.

### Best Practices
- [ ]  All routes are connected to the `index.js` file, which is located in the `routes` folder, and `app.js` contains one main route handled by routes.
- [x]  Asynchronous operations are implemented using promises or async/await.
- [x]  Validation is described in a separate module.
- [x]  Logging is set up:
  - [x] All requests and responses are logged to the `request.log` file.
  - [x] All errors are logged to the `error.log` file.
  - [x] Log files aren't added to the git repository.
- [x]  Errors are handled by a centralized handler.
- [x]  Centralized error handling is described inside a separate module.
- [x]  The application API is located in an /api subdirectory or on an api. subdomain (not just name.zone)
  - [x] Correct:  domain-name.tk/api or api.domain-name.tk
  - [x] Incorrect: domain-name.tk


### Recommendations
- [x]  For API errors, classes have been created to extend the Error constructor.
- [x]  The Helmet module is used to set security-related headers.
- [ ]  Configuration and constants are stored in separate files:
  - [ ] The Mongo server address and the private key for the JWT in development mode are stored inside a separate configuration file.
  - [ ] Application constants (response and error messages) are stored inside a separate file with constants.
- [ ]  A rate limiter is set up: the number of requests from a single IP address is limited to a particular value in a given amount of time.
- [ ]  The rate limiter is configured in a separate file and imported into `app.js`.

## Number of points: 73

## Additional comments:
- Please, add the description of the project and its links to the README file because it is empty.
- The database address should be set to the default value so that when run in dev mode, the code can run and work without an '.env' file

**Comment by adzhenalieva** [comment]
# Summary:
## Backend

### Performance Criteria
- [x]  The repository contains all the necessary infrastructure files:
  - [x] `package.json`;
  - [x] `.editorconfig`;
  - [x] `.eslintrc` is required for extending the configuration of airbnb-base
		- [x] `package.json` contains the `devDependencies` needed for the linter to work correctly
		- [x] An exception for `_id` is added
		- [x] The following rules are forbidden: `eslint-disable`, `eslint-disable-line`, and `eslint-disable-next-line`
  - [x] `.gitignore` should contain at least the `node_modules` folder
- [x]  There are no lint errors. When running `npx eslint .` they should be absent.
- [x]  The scripts section of the package.json file contains the following:
  - [x] An `npm run start` command that starts the server on `localhost:3000`.
  - [x] An `npm run dev` command that starts the server on `localhost:3000` with hot reloading.
- [ ]  The following routes function as described:
  - [x] A request to `GET /users/me` returns information about the user (email and name).
  - [x] `POST /signup` creates a user with the data passed inside the request body.
  - [x] `POST /signin` returns a JWT when the correct email and password are passed in the request body.
  - [x] `GET /articles` returns all articles saved by the user.
  - [ ] `POST /articles` creates an article with the data passed inside the request body.
      _The article's fields should not have been changed. According to the task, there should be the following fields: https://snipboard.io/DKXYZ4.jpg_
  - [x] `DELETE /articles/:articleId` deletes the saved article using `_id`.
- [x]  Users can't delete saved articles from other user profiles.
- [x]  All routes are protected with authorization, except for `/signin` and `/signup`.
- [x]  User routes and article routes are described in separate files.
- [x]  API errors are handled:
  - [x] Error status codes are used: 400, 401, 403, 404, 409, 500.
  - [x] If something is wrong with the request, the server returns a response with an error message and a corresponding status.
  - [x] The error message matches its type.
  - [x] Asynchronous handlers end with a `catch()` block.
  - [x] The API does not return standard database or Node.js errors.
- [x]  Safe password storage has been implemented:
  - [x] Passwords are stored in a hashed form.
  - [x] The API does not return a password hash to the client.
- [x]  Validation implemented correctly:
  - [x] Requests are validated before being passed to the controller. The body and (where applicable) headers and parameters are checked against the corresponding schemas. If a request doesn't match the schema, the processing is not passed to the controller and the client receives a validation error.
  - [x] Data is validated before being added to the database.
- [x]  In production mode, the database address is taken from `process.env`.
- [x]  The server can be accessed via HTTPS using the domain specified in README.md.
- [x]  Storing the secret key for creating a JWT is implemented correctly:
  - [x] In production (i.e., when deployed to the server), the secret key should be stored in a .env file, and this file should not be added to Git.
  - [x] In development (i.e., when run on localhost), the code should run and function correctly, even though there is no .env file present.

### Best Practices
- [ ]  All routes are connected to the `index.js` file, which is located in the `routes` folder, and `app.js` contains one main route handled by routes.
- [x]  Asynchronous operations are implemented using promises or async/await.
- [x]  Validation is described in a separate module.
- [x]  Logging is set up:
  - [x] All requests and responses are logged to the `request.log` file.
  - [x] All errors are logged to the `error.log` file.
  - [x] Log files aren't added to the git repository.
- [x]  Errors are handled by a centralized handler.
- [x]  Centralized error handling is described inside a separate module.
- [x]  The application API is located in an /api subdirectory or on an api. subdomain (not just name.zone)
  - [x] Correct:  domain-name.tk/api or api.domain-name.tk
  - [x] Incorrect: domain-name.tk


### Recommendations
- [x]  For API errors, classes have been created to extend the Error constructor.
- [x]  The Helmet module is used to set security-related headers.
- [ ]  Configuration and constants are stored in separate files:
  - [ ] The Mongo server address and the private key for the JWT in development mode are stored inside a separate configuration file.
  - [ ] Application constants (response and error messages) are stored inside a separate file with constants.
- [ ]  A rate limiter is set up: the number of requests from a single IP address is limited to a particular value in a given amount of time.
- [ ]  The rate limiter is configured in a separate file and imported into `app.js`.

## Number of points: 73

## Additional comments:
- **Please, add the description of the project and its links to the README file. Because the README file is empty.**
- The database address should be set to the default value so that when run in dev mode, the code can run and work without an '.env' file

**Comment by skovakina** [comment]
Hello!
First off, I truly appreciate the time and effort you put into reviewing my code. Every review session is an invaluable learning opportunity for me, and I'm grateful for the insights you share.

I have a question that I hope you won't mind helping me with. I aligned the properties of the data in my site's API with those of the external news API, aiming to simplify the component responsible for rendering the cards. I assumed that maintaining consistency between these data structures would make the rendering process more straightforward.

Could you please share your thoughts on this approach? Thank you!

**Comment by adzhenalieva** [comment]
> Hello! First off, I truly appreciate the time and effort you put into reviewing my code. Every review session is an invaluable learning opportunity for me, and I'm grateful for the insights you share.
> 
> I have a question that I hope you won't mind helping me with. I aligned the properties of the data in my site's API with those of the external news API, aiming to simplify the component responsible for rendering the cards. I assumed that maintaining consistency between these data structures would make the rendering process more straightforward.
> 
> Could you please share your thoughts on this approach? Thank you!

Hello! Thank you for your question. I will check the API, maybe I've missed the updates of fields. I will get back to you as soon as possible.

**Comment by adzhenalieva** [comment]
@skovakina Hi! I've checked the news API (https://newsapi.org/), and here is the list of fields. I’ve marked with '+' the fields that your schema already has:

`source.name (should be instead of keyword)`
`author`
`title +`
`description `
`url +`
`urlToImage +`
`publishedAt +`
`content +`
`owner + (will be added in the controller, it will not come in the req.body)`

Please, send the project for review one more time. I am very sorry for the delay.

**Comment by skovakina** [comment]
@adzhenalieva Thanks for taking the time to look into my question!

I'm still a bit unsure about the article schema. According to the first-stage instructions, I should extract the publisher's name from `source.name`, while `author` is apparently not used for the markup. As for the keyword, it's meant to be whatever word is used to search for the article if I understand it correctly. I've been tracking this keyword on the frontend and including it with requests to the site's API.

**Comment by adzhenalieva** [comment]
> @adzhenalieva Thanks for taking the time to look into my question!
> 
> I'm still a bit unsure about the article schema. According to the first-stage instructions, I should extract the publisher's name from `source.name`, while `author` is apparently not used for the markup. As for the keyword, it's meant to be whatever word is used to search for the article if I understand it correctly. I've been tracking this keyword on the frontend and including it with requests to the site's API.

I see, you may leave the `keyword` and use the `source.name` and ignore the 'author' field as it will not be used in the markup

**Comment by skovakina** [comment]
> > @adzhenalieva Thanks for taking the time to look into my question!
> > I'm still a bit unsure about the article schema. According to the first-stage instructions, I should extract the publisher's name from `source.name`, while `author` is apparently not used for the markup. As for the keyword, it's meant to be whatever word is used to search for the article if I understand it correctly. I've been tracking this keyword on the frontend and including it with requests to the site's API.
> 
> I see, you may leave the `keyword` and use the `source.name` and ignore the 'author' field as it will not be used in the markup

Thank you! I also changed `article.content` to `article.description` according to the instruction.

**Comment by adzhenalieva** [comment]
# Summary:
## Backend

### Performance Criteria
- [x]  The repository contains all the necessary infrastructure files:
  - [x] `package.json`;
  - [x] `.editorconfig`;
  - [x] `.eslintrc` is required for extending the configuration of airbnb-base
		- [x] `package.json` contains the `devDependencies` needed for the linter to work correctly
		- [x] An exception for `_id` is added
		- [x] The following rules are forbidden: `eslint-disable`, `eslint-disable-line`, and `eslint-disable-next-line`
  - [x] `.gitignore` should contain at least the `node_modules` folder
- [x]  There are no lint errors. When running `npx eslint .` they should be absent.
- [x]  The scripts section of the package.json file contains the following:
  - [x] An `npm run start` command that starts the server on `localhost:3000`.
  - [x] An `npm run dev` command that starts the server on `localhost:3000` with hot reloading.
- [x]  The following routes function as described:
  - [x] A request to `GET /users/me` returns information about the user (email and name).
  - [x] `POST /signup` creates a user with the data passed inside the request body.
  - [x] `POST /signin` returns a JWT when the correct email and password are passed in the request body.
  - [x] `GET /articles` returns all articles saved by the user.
  - [x] `POST /articles` creates an article with the data passed inside the request body.
  - [x] `DELETE /articles/:articleId` deletes the saved article using `_id`.
- [x]  Users can't delete saved articles from other user profiles.
- [x]  All routes are protected with authorization, except for `/signin` and `/signup`.
- [x]  User routes and article routes are described in separate files.
- [x]  API errors are handled:
  - [x] Error status codes are used: 400, 401, 403, 404, 409, 500.
  - [x] If something is wrong with the request, the server returns a response with an error message and a corresponding status.
  - [x] The error message matches its type.
  - [x] Asynchronous handlers end with a `catch()` block.
  - [x] The API does not return standard database or Node.js errors.
- [x]  Safe password storage has been implemented:
  - [x] Passwords are stored in a hashed form.
  - [x] The API does not return a password hash to the client.
- [x]  Validation implemented correctly:
  - [x] Requests are validated before being passed to the controller. The body and (where applicable) headers and parameters are checked against the corresponding schemas. If a request doesn't match the schema, the processing is not passed to the controller and the client receives a validation error.
  - [x] Data is validated before being added to the database.
- [x]  In production mode, the database address is taken from `process.env`.
- [x]  The server can be accessed via HTTPS using the domain specified in README.md.
- [x]  Storing the secret key for creating a JWT is implemented correctly:
  - [x] In production (i.e., when deployed to the server), the secret key should be stored in a .env file, and this file should not be added to Git.
  - [x] In development (i.e., when run on localhost), the code should run and function correctly, even though there is no .env file present.

### Best Practices
- [ ]  All routes are connected to the `index.js` file, which is located in the `routes` folder, and `app.js` contains one main route handled by routes.
- [x]  Asynchronous operations are implemented using promises or async/await.
- [x]  Validation is described in a separate module.
- [x]  Logging is set up:
  - [x] All requests and responses are logged to the `request.log` file.
  - [x] All errors are logged to the `error.log` file.
  - [x] Log files aren't added to the git repository.
- [x]  Errors are handled by a centralized handler.
- [x]  Centralized error handling is described inside a separate module.
- [x]  The application API is located in an /api subdirectory or on an api. subdomain (not just name.zone)
  - [x] Correct:  domain-name.tk/api or api.domain-name.tk
  - [x] Incorrect: domain-name.tk


### Recommendations
- [x]  For API errors, classes have been created to extend the Error constructor.
- [x]  The Helmet module is used to set security-related headers.
- [ ]  Configuration and constants are stored in separate files:
  - [ ] The Mongo server address and the private key for the JWT in development mode are stored inside a separate configuration file.
  - [ ] Application constants (response and error messages) are stored inside a separate file with constants.
- [ ]  A rate limiter is set up: the number of requests from a single IP address is limited to a particular value in a given amount of time.
- [ ]  The rate limiter is configured in a separate file and imported into `app.js`.

## Number of points: 95

## Additional comments:
- **Please, add the description of the project and its links to the README file. Because the README file is empty.**
- The database address should be set to the default value so that when run in dev mode, the code can run and work without an '.env' file
- Please, do not forget to update the production server, because it requires the "old" fields

**Pull request merged**
